### ISSUE TITLE
Will there be an 0.5.5 melonloader release?

### ISSUE THREAD

**Issue by Jonyboylovespie** [BepInEx/BepInEx.MelonLoader.Loader#3]
Hello, as you may or may not know there has been an 0.5.5 melonloader release. Will this be updated to that version? Thank you.

**Comment by bbepis** [comment]
Has been updated to 0.5.7. Might be updated to 0.6.x in the future

**Comment by win0809** [comment]
> Hello, as you may or may not know there has been an 0.5.5 melonloader release. Will this be updated to that version? Thank you.

Hello can you update to support Melonloader 0.70? thank you
